const list = [
    {
        order: 1,
        category: 'POSTER',
        name: 'poster',
        mainImg: '/images/product/POSTER-MAIN.jpg',
        imgType: '.png',
        icon: '/images/icons/poster.png',
        subLength: 5,
        title: '포스터' ,
        subTitle: '포스터 서브타이틀' ,
        desc: '포스터 | 공모전 | 기타등등', 
    },
    {
        order: 2,
        category: 'BOOK',
        name: 'book',
        mainImg: '/images/product/BOOK-MAIN.jpg',
        imgType: '.jpg',
        icon: '/images/icons/book.png',
        subLength: 2,
        title: '북' ,
        subTitle: '북 서브타이틀' ,
        desc: '북 | 책 | 기타등등', 
    },
      {
        order: 3,
        category: 'LEAFLET',
        name: 'leaflet',
        mainImg: '/images/product/LEAFLET-MAIN.png',
        imgType: '.png',
        icon: '/images/icons/leaflet.png',
        subLength: 3,
        title: '리플렛' ,
        subTitle: '리플렛 서브타이틀' ,
        desc: '리플렛 | 뭐지요 | 기타등등',  
    },
    {
        order: 4,
        category: 'BANNER',
        name: 'banner',
        mainImg: '/images/product/BANNER-MAIN.png',
        imgType: '.png',
        icon: '/images/icons/banner.png',
        subLength: 5,
        title: '배너' ,
        subTitle: '배너 서브타이틀' ,
        desc: '배너 | 공모전 | 기타등등', 
    },
    {
        order: 5,
        category: 'SINGLE',
        name: 'single',
        mainImg: '/images/product/SINGLE-MAIN.png',
        imgType: '.png',
        icon: '/images/icons/single.png',
        subLength: 5,
        title: '싱글페이지' ,
        subTitle: '싱글페이지 서브타이틀' ,
        desc: '싱글페이지 | 책 | 기타등등', 
    },
      {
        order: 6,
        category: 'BRANDING',
        name: 'branding',
        mainImg: '/images/product/BRANDING-MAIN.png',
        imgType: '.png',
        icon: '/images/icons/branding.png',
        subLength: 2,
        title: '브랜딩' ,
        subTitle: '브랜딩 서브타이틀' ,
        desc: '브랜딩 | 하는거 | 기타등등',  
    },
    {
        order: 7,
        category: 'PROMOTION',
        name: 'promotion',
        mainImg: '/images/product/PROMOTION-MAIN.png',
        imgType: '.png',
        icon: '/images/icons/promotion.png',
        subLength: 2,
        title: '프로모션' ,
        subTitle: '프로모션 서브타이틀' ,
        desc: '프로모션 | 4P | 기타등등', 
    },
    {
        order: 8,
        category: 'SIGNBOARD',
        name: 'signboard',
        mainImg: '/images/product/SIGNBOARD-MAIN.jpg',
        imgType: '.png',
        icon: '/images/icons/signboard.png',
        subLength: 3,
        title: '사인보드' ,
        subTitle: '사인보드 서브타이틀' ,
        desc: '사인보드 | 싸인아님 | 기타등등', 
    },
      {
        order: 9,
        category: 'BROCHURE',
        name: 'brochure',
        mainImg: '/images/product/BROCHURE-MAIN.png',
        imgType: '.png',
        icon: '/images/icons/brochure.png',
        subLength: 4,
        title: '브로셔' ,
        subTitle: '브로셔 서브타이틀' ,
        desc: '브로셔 | 입니다 | 기타등등',  
    },
]

export default list;